"""cria contract_messages

Revision ID: 362740797e08
Revises: 4ef4e42079c6
Create Date: 2026-07-30 15:22:15.623869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '362740797e08'
down_revision: Union[str, Sequence[str], None] = '4ef4e42079c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_messages',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('humano', 'sistema', name='message_kind'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('mentioned_user_ids', postgresql.ARRAY(sa.Uuid()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("(kind = 'humano' AND author_id IS NOT NULL) OR (kind = 'sistema' AND author_id IS NULL)", name='ck_message_autor_conforme_tipo'),
    sa.ForeignKeyConstraint(['author_id'], ['public.platform_users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['contract_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_messages_created_at'), 'contract_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_contract_messages_request_id'), 'contract_messages', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_messages_request_id'), table_name='contract_messages')
    op.drop_index(op.f('ix_contract_messages_created_at'), table_name='contract_messages')
    op.drop_table('contract_messages')
    # ### end Alembic commands ###

    # O autogenerate não descarta o tipo; sem isto ele fica órfão no schema e o upgrade
    # seguinte falha com "type already exists".
    op.execute("DROP TYPE IF EXISTS message_kind")
