"""cria contract_requests

Revision ID: 4ef4e42079c6
Revises: de7ce3c0fcaf
Create Date: 2026-07-30 12:55:45.478941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef4e42079c6'
down_revision: Union[str, Sequence[str], None] = 'de7ce3c0fcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_requests',
    sa.Column('request_number', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('origin', sa.Enum('modelo_interno', 'minuta_terceiro', 'sem_documento', name='request_origin'), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('counterparty_raw', sa.String(length=255), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('desired_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('aberta', 'em_triagem', 'convertida', 'recusada', 'cancelada', name='request_status'), nullable=False),
    sa.Column('triaged_by', sa.Uuid(), nullable=True),
    sa.Column('triaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['contract_categories.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['public.platform_users.id'], ),
    sa.ForeignKeyConstraint(['triaged_by'], ['public.platform_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number')
    )
    op.create_index(op.f('ix_contract_requests_category_id'), 'contract_requests', ['category_id'], unique=False)
    op.create_index(op.f('ix_contract_requests_deleted_at'), 'contract_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contract_requests_requester_id'), 'contract_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_contract_requests_status'), 'contract_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_requests_status'), table_name='contract_requests')
    op.drop_index(op.f('ix_contract_requests_requester_id'), table_name='contract_requests')
    op.drop_index(op.f('ix_contract_requests_deleted_at'), table_name='contract_requests')
    op.drop_index(op.f('ix_contract_requests_category_id'), table_name='contract_requests')
    op.drop_table('contract_requests')
    # ### end Alembic commands ###

    # Sem schema qualificado: os tipos de tenant vivem dentro do próprio schema e são
    # resolvidos pelo search_path. `drop_table` não os remove — ficariam órfãos e o
    # upgrade seguinte falharia com "type already exists".
    op.execute("DROP TYPE IF EXISTS request_status")
    op.execute("DROP TYPE IF EXISTS request_origin")
