"""cria catalogo da plataforma

Revision ID: 5213d37a81c1
Revises: 
Create Date: 2026-07-30 12:28:17.950759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5213d37a81c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('code', sa.Enum('starter', 'growth', 'enterprise', name='plan_code', schema='public'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('seat_limit', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='public'
    )
    op.create_table('platform_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_platform_users_email'), 'platform_users', ['email'], unique=True, schema='public')
    op.create_table('tenants',
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector_pack', sa.Enum('generico', 'juridico_servicos', 'compras_fornecedores', 'rh_pessoas', 'comercial', 'imobiliario', name='sector_pack', schema='public'), nullable=False),
    sa.Column('status', sa.Enum('provisionando', 'ativo', 'trial', 'suspenso', 'cancelado', name='tenant_status', schema='public'), nullable=False),
    sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenants_slug'), 'tenants', ['slug'], unique=True, schema='public')
    op.create_table('subscriptions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('gateway_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'canceled', name='subscription_status', schema='public'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['public.plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False, schema='public')
    op.create_table('tenant_integrations',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('clicksign', 'docusign', 'evolution_whatsapp', name='integration_provider', schema='public'), nullable=False),
    sa.Column('credentials', sa.LargeBinary(), nullable=False),
    sa.Column('is_managed_by_pacta', sa.Boolean(), nullable=False),
    sa.Column('configured_by', sa.Uuid(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configured_by'], ['public.platform_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', name='uq_integration_tenant_provider'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenant_integrations_tenant_id'), 'tenant_integrations', ['tenant_id'], unique=False, schema='public')
    op.create_table('tenant_memberships',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'juridico', 'aprovador', 'gestor_contratos', 'visualizador', name='tenant_role', schema='public'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['public.tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.platform_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_membership_tenant_user'),
    schema='public'
    )
    op.create_index(op.f('ix_public_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_tenant_memberships_user_id'), 'tenant_memberships', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_tenant_memberships_user_id'), table_name='tenant_memberships', schema='public')
    op.drop_index(op.f('ix_public_tenant_memberships_tenant_id'), table_name='tenant_memberships', schema='public')
    op.drop_table('tenant_memberships', schema='public')
    op.drop_index(op.f('ix_public_tenant_integrations_tenant_id'), table_name='tenant_integrations', schema='public')
    op.drop_table('tenant_integrations', schema='public')
    op.drop_index(op.f('ix_public_subscriptions_tenant_id'), table_name='subscriptions', schema='public')
    op.drop_table('subscriptions', schema='public')
    op.drop_index(op.f('ix_public_tenants_slug'), table_name='tenants', schema='public')
    op.drop_table('tenants', schema='public')
    op.drop_index(op.f('ix_public_platform_users_email'), table_name='platform_users', schema='public')
    op.drop_table('platform_users', schema='public')
    op.drop_table('plans', schema='public')
    # ### end Alembic commands ###

    # Descarte dos tipos ENUM — escrito à mão, o autogenerate não gera.
    # `drop_table` não remove o tipo que a coluna usava: ele fica órfão no schema e o
    # upgrade seguinte falha com "type ... already exists". Sem estas linhas o downgrade
    # é irreversível na prática.
    for enum_name in (
        "plan_code",
        "sector_pack",
        "tenant_status",
        "subscription_status",
        "integration_provider",
        "tenant_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS public.{enum_name}")
